server:
    port: 9090
logging:
    level:
        tk.mybatis: TRACE
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://192.168.199.222:3306/test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true
    slave:
        url: jdbc:mysql://192.168.199.222:3306/test1?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true

# mybatis配置
mybatis:
    type-aliases-package: cn.com.hrl.pojo
    mapper-locations: classpath*:cn/com/hrl/**/mapping/*.xml
# 映射Mapper
mapper:
    mappers:
        - cn.com.hrl.database.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
# 打印sql
spring:
  jps:
    showsql: true